# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-07 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='user',
        ),
    ]
